### ISSUE TITLE
ER-Diagram Check

### ISSUE THREAD

**Issue by ghost** [Eckener-Schule/it-ausleihe#52]
Checking and (if needed) correcting the ER-Diagram for the project.

**Comment by JacobPruetz** [comment]
ER-Diagram Issues:
- Entity "device" 
Missing propertie "status" to show the current status of the device (Possible Status Values: available, lent, administration)
- Entitiy "loan" 
loan is not an entity, it is an relation
Missing propertie teacher to show the teacher of the lesson where the borrower lends the device
- What is when an teacher want to lent an device?
Where do we have the teachers?
Is an teacher also a borrower like a student? 
Possible solutions:
1. New entity "teacher"
2. Change entity "borrower" to insert teacher and student

**Comment by JacobPruetz** [comment]
![it-ausleihe_ER-Modell](https://user-images.githubusercontent.com/38519584/73917789-685bf880-48c0-11ea-8285-03bbadc89c20.png)

**Comment by ghost** [comment]
@JacobPruetz created an updated version of the ER-Diagram which added to the master branch in merge #82 and moved to the docs folder.

**Comment by cedFlei** [comment]
I helped Jacob with the rewiev of the ER-Diagram
