### ISSUE TITLE
UI doesn't load properly

### ISSUE THREAD

**Issue by ghost** [Eckener-Schule/it-ausleihe#78]
Reported by @ggarak and @laura2605:
On loading the current version of the main branch's index.php, the UI doesn't show up correctly and the browser throws several errors in the dev-tools.

**Comment by daniel100097** [comment]
Current version is not affected.

**Comment by MarcelMoeller** [comment]
This seems to happen on installations where the project is not on root level because the path to the assets is absolute. So **http://localhost/PHP/it-ausleihe/** does not work but **http://localhost/** does. A solution would be to change the asset paths to relative.

**Comment by ghost** [comment]
The issue apparently was resolved for the affected members by just pulling the up-to-date version of the project.
The comment by @MarcelMoeller does however bring up a good suggestion. Any reason not to do that?

**Comment by MarcelMoeller** [comment]
The problem i mentioned got fixed in the current version. I still had a old version of the header.php and footer.php so the problem with the absolute paths is fixed now.

**Comment by ghost** [comment]
I see, closing this then.
