### ISSUE TITLE
Moving database class out of it's folder into "Classes" folder so it will be recognised from autoloader.

### ISSUE THREAD

**Issue by LinkJp** [Eckener-Schule/it-ausleihe#80]
Hi,
i just saw that the Database class was in it's own folder and therefore not recognizable by the autoloader.
I Would like to quickly remove that folder and place the file into the "Classes" folder.
Also, I would like to change the first character to uppercase as classes should start with that.

Greetings

**Comment by MarcelMoeller** [comment]
There is actually no need to move the file. The only thing that needs to be added is the path to the new folder inside the autoloaders paths array e.g. **Classes/Db**. The autoloader will automaticly load all folder inside the $paths array.

**Comment by ghost** [comment]
You are correct about that @MarcelMoeller, it wouldn't strictly be necessary.
But considering the Database.php class in this case is actually just that - a class to handle database connections - and we have less than 10 classes in total, I don't see why it had to be in a subfolder in the first place.

No need for unnecessarily complex folder structure, closing this for now.
